"""Creacion de tablas iniciales

Revision ID: 739c68f31939
Revises: 
Create Date: 2026-03-04 19:10:48.127625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739c68f31939'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo_postal', sa.Integer(), nullable=False),
    sa.Column('limite_velocidad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scooter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('bateria', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'en_uso', 'mantenimiento', 'sin_bateria', name='scooterstatus'), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zona_id'], ['zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scooter')
    op.drop_table('zone')
    # ### end Alembic commands ###
