"""Nuevo campo en tabla scooters

Revision ID: 9469f50e3566
Revises: 739c68f31939
Create Date: 2026-03-04 19:12:20.946380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9469f50e3566'
down_revision: Union[str, Sequence[str], None] = '739c68f31939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scooter', sa.Column('puntuacion_usuario', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scooter', 'puntuacion_usuario')
    # ### end Alembic commands ###
