"""Añadido un nuevo campo a la tabla scooter

Revision ID: 228f2c99dd69
Revises: 6e2a27ed7366
Create Date: 2026-03-01 14:39:33.884144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228f2c99dd69'
down_revision: Union[str, Sequence[str], None] = '6e2a27ed7366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
