"""Nuevo campo en la tabla scooters

Revision ID: 2a0f605a0dbf
Revises: 922a8fcfee8b
Create Date: 2026-03-02 15:29:13.027572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0f605a0dbf'
down_revision: Union[str, Sequence[str], None] = '922a8fcfee8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scooter', sa.Column('puntuacion_usuario', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scooter', 'puntuacion_usuario')
    # ### end Alembic commands ###
